#########################################################################################################################
######                                                                    #####                                            
#     # #####   ####  #    # ###### ##### #    # ###### #    #  ####     #     # ###### ##### ##### # #    #  ####   ####  
#     # #    # #    # ##  ## #        #   #    # #      #    # #         #       #        #     #   # ##   # #    # #      
######  #    # #    # # ## # #####    #   ###### #####  #    #  ####      #####  #####    #     #   # # #  # #       ####  
#       #####  #    # #    # #        #   #    # #      #    #      #          # #        #     #   # #  # # #  ###      # 
#       #   #  #    # #    # #        #   #    # #      #    # #    #    #     # #        #     #   # #   ## #    # #    # 
#       #    #  ####  #    # ######   #   #    # ######  ####   ####      #####  ######   #     #   # #    #  ####   ####  
##########################################################################################################################

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 50Gi
  service:
    type: LoadBalancer
# Configuration of subcharts defined in Chart.yaml

## alertmanager sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/alertmanager
##
alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: true
  persistence:
    storageClass: gp2
    size: 20Gi
  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
## kube-state-metrics sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
##
kube-state-metrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: true
## prometheus-node-exporter sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
##
prometheus-node-exporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: true
  rbac:
    pspEnabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
## prometheus-pushgateway sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway
##
prometheus-pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: true
  # Optional service annotations
  serviceAnnotations:
    prometheus.io/probe: pushgateway
#
######################################################################################################

#####                                                #####                                            
#     # #####    ##   ######   ##   #    #   ##      #     # ###### ##### ##### # #    #  ####   ####  
#       #    #  #  #  #       #  #  ##   #  #  #     #       #        #     #   # ##   # #    # #      
#  #### #    # #    # #####  #    # # #  # #    #     #####  #####    #     #   # # #  # #       ####  
#     # #####  ###### #      ###### #  # # ######          # #        #     #   # #  # # #  ###      # 
#     # #   #  #    # #      #    # #   ## #    #    #     # #        #     #   # #   ## #    # #    # 
#####  #    # #    # #      #    # #    # #    #     #####  ######   #     #   # #    #  ####   #### 

######################################################################################################

## Expose the grafana service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
grafana:
  service:
    type: LoadBalancer
  # Set the ip family policy to configure dual-stack see [Configure dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services)
  ipFamilyPolicy: ""
  # Sets the families that should be supported and the order in which they should be applied to ClusterIP as well. Can be IPv4 and/or IPv6.
  ipFamilies: []
  loadBalancerIP: ""
  loadBalancerClass: ""
  loadBalancerSourceRanges: []
  port: 80
  targetPort: 3000
  # targetPort: 4181 To be used with a proxy extraContainer

  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  ##
  persistence:
    enabled: true
    storageClassName: gp2
    ## (Optional) Use this to bind the claim to an existing PersistentVolume (PV) by name.
    volumeName: ""
    accessModes:
      - ReadWriteOnce
    size: 50Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # selectorLabels: {}
    ## Sub-directory of the PV to mount. Can be templated.
    # subPath: ""
    ## Name of an existing PVC. Can be templated.
    # existingClaim:
    ## Extra labels to apply to a PVC.
    extraPvcLabels: {}
    disableWarning: false
