apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: keycloak-demo
  labels:
    type: local
    app: postgres
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"
