apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "keycloak-demo"
  namespace: "keycloak-demo"
spec:
  selector:
    matchLabels:
      app: "keycloak-demo"
  replicas: 1
  #strategy:
  #  type: "RollingUpdate"
  #  rollingUpdate:
  #   maxSurge: 1
  #    maxUnavailable: 1
  #minReadySeconds: 5
  template:
    metadata:
      labels:
        app: "keycloak-demo"
    spec:
      containers:
        - name: "keycloak-demo"
          image: public.ecr.aws/i0v0m7z7/class06/kc-demo:latest
          imagePullPolicy: "Always"
          env:
            - name: "KC_BOOTSTRAP_ADMIN_USERNAME"
              value: "admin"
            - name: "KC_BOOTSTRAP_ADMIN_PASSWORD"
              value: "admin"
            - name: "KC_DB"
              value: "postgres"
            - name: "KC_DB_URL_HOST"
              value: "postgres"
            - name: "KC_DB_URL_DATABASE"
              value: "keycloak"
            - name: "KC_DB_USERNAME"
              value: "keycloak"
            - name: "KC_DB_PASSWORD"
              value: "123456"
          ports:
            - name: "http"
              containerPort: 8080
            - name: "https"
              containerPort: 8443
#          readinessProbe:
#            httpGet:
#              path: "/auth/realms/master"
#              port: 8080
