apiVersion: "v1"
kind: "Service"
metadata:
  name: "keycloak-demo"
  labels:
    app: "keycloak-demo"
spec:
  selector:
    app: "keycloak-demo"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
